### ISSUE TITLE
Stream error: 12 UNIMPLEMENTED: subscribe_mempool is deprecated

### ISSUE THREAD

**Issue by alexandr-kazakov** [jito-labs/jito-ts#25]
```
Stream error: 12 UNIMPLEMENTED: subscribe_mempool is deprecated
    at ClientReadableStreamImpl.<anonymous> (/.../jito-ts/dist/sdk/block-engine/searcher.js:171:27)
    at ClientReadableStreamImpl.emit (node:events:515:28)
    at Object.onReceiveStatus (/.../jito-ts/node_modules/@grpc/grpc-js/build/src/client.js:358:28)
    at Object.onReceiveStatus (/.../jito-ts/node_modules/@grpc/grpc-js/build/src/client-interceptors.js:323:181)
    at /.../jito-ts/node_modules/@grpc/grpc-js/build/src/resolving-call.js:129:78
    at process.processTicksAndRejections (node:internal/process/task_queues:77:11)

Node.js v21.1.0
```

Any Idea how I can solve it? Thanks

**Comment by p0st1t** [comment]
Hello, i have exactly the same issue...

Did you find a solution please?

**Comment by alexandr-kazakov** [comment]
@p0st1t no i didn't find a solution, I'm using Jito only for creating the bundles, but for subscribe a mempool I'm using another solution. You can see my project with subscribe a mempool example here:  https://github.com/alexandr-kazakov/solana-crendel-bot

**Comment by p0st1t** [comment]
Thank you very much Alex, very interesting!

**Comment by InfernalHeir** [comment]
@alexandr-kazakov It's kind of snipper bot. Thankyou very much.
